language: java

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

env:
  JDBC_DATABASE_URL="jdbc:postgresql://localhost/travis_ci_test?user=postgres&password="

jdk:
  - openjdk14

after_success:
  - bash <(curl -s https://codecov.io/bash)