services:
  - postgresql

jdk:
  - openjdk14

before_script:
  - psql --version
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - mvn clean test
  - bash <(curl -s https://codecov.io/bash) -c -F unit-tests
  - mvn clean integration-test -Dtest=**/*IT
  - bash <(curl -s https://codecov.io/bash) -c -F integration-tests

env:
  global:
    - JDBC_DATABASE_URL="jdbc:postgresql://localhost:5432/travis_ci_test?user=postgres&password="