openapi: 3.0.0
info:
  title: Chess Web API
  description: Description
  version: 1.0.0
servers:
  - url: 'http://localhost:37629/api/v1/'
    description: Local Test Server
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
  responses:
    UnauthorizedError:
      description: API key is invalid
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                description: An error string containing information about the unauthorized error
  schemas:
    Game:
      type: object
      properties:
        id:
          type: string


security:
  - ApiKeyAuth: []

paths:
  /games/:
    post:
      description: Creates a new game and joins it as a random player
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: A JSON object containing information about the created game
          content:
            application/json:
              schema:
                type: object
                properties:
                  created:
                    description: A string containing the id of the newly created game
                    type: string
                    example: dodblmgo88px61tf
        '401':
          $ref: "#/components/responses/UnauthorizedError"