name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    env:
      JDBC_DATABASE_URL: jdbc:postgresql://localhost:5432/test?user=postgres&password=postgres
      REDIS_URL: redis://localhost:6379

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: External Dependencies
        run: |
          source scripts/get_stockfish.sh
          echo "STOCKFISH_PATH=$STOCKFISH_PATH" >> $GITHUB_ENV
      - name: Create Postgres Table
        run: PGPASSWORD=postgres psql -h localhost -p 5432 -U postgres -c "CREATE DATABASE test"
      - name: Run Integration Tests
        run: mvn clean integration-test -Dtest=**/*IT -DfailIfNoTests=false
      - uses: codecov/codecov-action@v1
        with:
          flags: integration-tests

  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Run Unit Tests
        run: mvn clean test
      - uses: codecov/codecov-action@v1
        with:
          flags: unit-tests